MISSING_VALUE = "MISSING_VALUE"
POSITIVE_VALUE = "כן"
NEGATIVE_VALUE = "לא"
DATE_STRING_FORMAT = r'\d*[\./]\d*[\./]\d*'

NEEDLE_WIDTH_SYMBOL = "G"
NEEDLE_WIDTH_OPTIONS = ["12", "14", "18", "20", "22", "23"]